<a href="https://colab.research.google.com/github/drcruzm/calculo/blob/main/multiplicacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.random.seed(27)
A = np.random.randint(11,15,size = (3,3))
B = np.random.randint(11,15,size = (3,2))
print(f"Matrix A:\n {A}\n")
print(f"Matrix B:\n {B}\n")

Matrix A:
 [[14 11 11]
 [14 11 11]
 [12 11 12]]

Matrix B:
 [[12 12]
 [13 14]
 [14 13]]



In [12]:
A1 = A[2,:]
B1 = B[:,1]
print(A1)
print(B1)

[12 11 12]
[12 14 13]


In [13]:
C = np.dot(A1,B1)
print(C)

454


In [3]:
def multiply_matrix(A,B):
  global C
  if  A.shape[1] == B.shape[0]:
    C = np.zeros((A.shape[0],B.shape[1]),dtype = int)
    for row in range(rows):
        for col in range(cols):
            for elt in range(len(B)):
              C[row, col] += A[row, elt] * B[elt, col]
    return C
  else:
    return "Sorry, cannot multiply A and B."

In [6]:
rows = 3
cols = 2
D = multiply_matrix(A,B)
print(f"Matrix D:\n {D}\n")

Matrix D:
 [[465 465]
 [465 465]
 [455 454]]



In [5]:
C = A@B
print(C)

[[465 465]
 [465 465]
 [455 454]]


In [9]:
C = np.matmul(A,B)
print(C)

[[465 465]
 [465 465]
 [455 454]]
